### ISSUE TITLE
plot.hist1d legend and legend_loc seem redundant?

### ISSUE THREAD

**Issue by JS3xton** [rice-bioe/fc#122]
Could you get away with just `legend_loc`? Seems like if that's non-`None`, you can assume a legend and use `legend_loc` to describe the location string.

Also looks like you used `legend_loc` without `legend` in `plot.bar()`.

Could still use `legend` as variable name, just clarify in Parameters section that it's used to specify legend location.

**Comment by castillohair** [comment]
I think that's a little confusing, and would require more explanation since a single parameter would be doing more. I'd rather have more, simpler parameters.

Also, `plot.bar()` is not among us anymore. RIP
